# Generated by Django 4.0.4 on 2022-05-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_products_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categ',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
