# Generated by Django 4.0.4 on 2022-07-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_categ_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categ',
            options={},
        ),
    ]
